mex -v -compatibleArrayDims -O -D_USE_MATH_DEFINES COMPFLAGS='$COMPFLAGS /std:c++17'...
    -I"ruckig\include" sfun_motiongen.cpp ...
    ruckig/src/ruckig/brake.cpp ...
    ruckig/src/ruckig/position_first_step1.cpp ...
    ruckig/src/ruckig/position_first_step2.cpp ...
    ruckig/src/ruckig/position_second_step1.cpp ...
    ruckig/src/ruckig/position_second_step2.cpp ...
    ruckig/src/ruckig/position_third_step1.cpp ...
    ruckig/src/ruckig/position_third_step2.cpp ...
    ruckig/src/ruckig/velocity_second_step1.cpp ...
    ruckig/src/ruckig/velocity_second_step2.cpp ...
    ruckig/src/ruckig/velocity_third_step1.cpp ...
    ruckig/src/ruckig/velocity_third_step2.cpp